//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lehrstellensuchassistenz.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lehrstellensuchassistenz.Resources.Languages.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Firma hinzufügen.
        /// </summary>
        public static string BtnAddCompany {
            get {
                return ResourceManager.GetString("BtnAddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEWERBEN!.
        /// </summary>
        public static string BtnApplyBig {
            get {
                return ResourceManager.GetString("BtnApplyBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markierte löschen.
        /// </summary>
        public static string BtnBulkDelete {
            get {
                return ResourceManager.GetString("BtnBulkDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner wählen....
        /// </summary>
        public static string BtnChooseFolder {
            get {
                return ResourceManager.GetString("BtnChooseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auswahl aufheben.
        /// </summary>
        public static string BtnClearSelection {
            get {
                return ResourceManager.GetString("BtnClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortsetzen.
        /// </summary>
        public static string BtnContinue {
            get {
                return ResourceManager.GetString("BtnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop-Verknüpfung erstellen.
        /// </summary>
        public static string BtnCreateShortcut {
            get {
                return ResourceManager.GetString("BtnCreateShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einrichtung abschließen.
        /// </summary>
        public static string BtnFinishSetup {
            get {
                return ResourceManager.GetString("BtnFinishSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links verwalten / löschen.
        /// </summary>
        public static string BtnManageLinks {
            get {
                return ResourceManager.GetString("BtnManageLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📂 Bewerbungsordner.
        /// </summary>
        public static string BtnOpenAppFolder {
            get {
                return ResourceManager.GetString("BtnOpenAppFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📄 Lebenslauf öffnen.
        /// </summary>
        public static string BtnOpenResume {
            get {
                return ResourceManager.GetString("BtnOpenResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen speichern.
        /// </summary>
        public static string BtnSaveAll {
            get {
                return ResourceManager.GetString("BtnSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeres Dokument wählen.
        /// </summary>
        public static string BtnSelectEmptyTemplate {
            get {
                return ResourceManager.GetString("BtnSelectEmptyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generische Vorlage wählen.
        /// </summary>
        public static string BtnSelectGenericTemplate {
            get {
                return ResourceManager.GetString("BtnSelectGenericTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙ Einstellungen.
        /// </summary>
        public static string BtnSettings {
            get {
                return ResourceManager.GetString("BtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup starten.
        /// </summary>
        public static string BtnStartCleanup {
            get {
                return ResourceManager.GetString("BtnStartCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 Bewerbungstipps.
        /// </summary>
        public static string BtnTippsApplication {
            get {
                return ResourceManager.GetString("BtnTippsApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📝 Lebenslauftipps.
        /// </summary>
        public static string BtnTippsCV {
            get {
                return ResourceManager.GetString("BtnTippsCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verstanden.
        /// </summary>
        public static string BtnUnderstood {
            get {
                return ResourceManager.GetString("BtnUnderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigene Vorlage hochladen.
        /// </summary>
        public static string BtnUploadCustomTemplate {
            get {
                return ResourceManager.GetString("BtnUploadCustomTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigene Vorlage verwenden.
        /// </summary>
        public static string BtnUseCustomTemplate {
            get {
                return ResourceManager.GetString("BtnUseCustomTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App beim Windows-Start automatisch öffnen.
        /// </summary>
        public static string CheckAutostart {
            get {
                return ResourceManager.GetString("CheckAutostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop-Verknüpfung erstellen.
        /// </summary>
        public static string CheckCreateShortcut {
            get {
                return ResourceManager.GetString("CheckCreateShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komplette App entfernen (Programmordner löschen).
        /// </summary>
        public static string CheckDeleteAppFolder {
            get {
                return ResourceManager.GetString("CheckDeleteAppFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Benutzerdaten löschen (Firmen, Notizen, Registry).
        /// </summary>
        public static string CheckDeleteUserData {
            get {
                return ResourceManager.GetString("CheckDeleteUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link konnte nicht geöffnet werden.
        /// </summary>
        public static string ErrLinkOpened {
            get {
                return ResourceManager.GetString("ErrLinkOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Erstellen der Verknüpfung:.
        /// </summary>
        public static string ErrShortcut {
            get {
                return ResourceManager.GetString("ErrShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilder (*.png;*.jpg;*.jpeg)|*.png;*.jpg;*.jpeg.
        /// </summary>
        public static string FilterImages {
            get {
                return ResourceManager.GetString("FilterImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gefahrenzone.
        /// </summary>
        public static string GroupDangerZone {
            get {
                return ResourceManager.GetString("GroupDangerZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten &amp; Speicher.
        /// </summary>
        public static string GroupDataStorage {
            get {
                return ResourceManager.GetString("GroupDataStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allgemein.
        /// </summary>
        public static string GroupGeneral {
            get {
                return ResourceManager.GetString("GroupGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidebar Quicklinks.
        /// </summary>
        public static string GroupQuicklinks {
            get {
                return ResourceManager.GetString("GroupQuicklinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEINE LINKS.
        /// </summary>
        public static string HeaderMyLinks {
            get {
                return ResourceManager.GetString("HeaderMyLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notizen.
        /// </summary>
        public static string HeaderNotes {
            get {
                return ResourceManager.GetString("HeaderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTALE.
        /// </summary>
        public static string HeaderPortals {
            get {
                return ResourceManager.GetString("HeaderPortals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schnell-Einrichtung.
        /// </summary>
        public static string HeaderQuickSetup {
            get {
                return ResourceManager.GetString("HeaderQuickSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string HeaderSettings {
            get {
                return ResourceManager.GetString("HeaderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verknüpfung erstellen.
        /// </summary>
        public static string HeaderShortcut {
            get {
                return ResourceManager.GetString("HeaderShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Hinweis: Nach der Änderung startet die App automatisch neu..
        /// </summary>
        public static string HintRestartNote {
            get {
                return ResourceManager.GetString("HintRestartNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigene Links hinzufügen:.
        /// </summary>
        public static string LblAddCustomLinks {
            get {
                return ResourceManager.GetString("LblAddCustomLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktueller Speicherort für Benutzerdaten:.
        /// </summary>
        public static string LblCurrentStoragePath {
            get {
                return ResourceManager.GetString("LblCurrentStoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuletzt aktualisiert:.
        /// </summary>
        public static string LblLastUpdated {
            get {
                return ResourceManager.GetString("LblLastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link:.
        /// </summary>
        public static string LblLink {
            get {
                return ResourceManager.GetString("LblLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string LblName {
            get {
                return ResourceManager.GetString("LblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmenbild / Haus.
        /// </summary>
        public static string LblPhotoPlaceholderMain {
            get {
                return ResourceManager.GetString("LblPhotoPlaceholderMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken zum Auswählen.
        /// </summary>
        public static string LblPhotoPlaceholderSub {
            get {
                return ResourceManager.GetString("LblPhotoPlaceholderSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorschau Eigene Vorlage.
        /// </summary>
        public static string LblPreviewCustomTemplate {
            get {
                return ResourceManager.GetString("LblPreviewCustomTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie heißt die Firma?.
        /// </summary>
        public static string LblQuestionCompanyName {
            get {
                return ResourceManager.GetString("LblQuestionCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links zum Löschen auswählen:.
        /// </summary>
        public static string LblSelectLinksToDelete {
            get {
                return ResourceManager.GetString("LblSelectLinksToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string LblStatus {
            get {
                return ResourceManager.GetString("LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bist du sicher? Die App wird nach dem Cleanup beendet..
        /// </summary>
        public static string MsgCleanupConfirm {
            get {
                return ResourceManager.GetString("MsgCleanupConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du alle markierten Firmen wirklich löschen?.
        /// </summary>
        public static string MsgConfirmDeleteBulk {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteBulk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link(s) wirklich entfernen?.
        /// </summary>
        public static string MsgConfirmDeleteLinks {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du diese Firma wirklich löschen?.
        /// </summary>
        public static string MsgConfirmDeleteSingle {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen bestätigen.
        /// </summary>
        public static string MsgConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string MsgInfo {
            get {
                return ResourceManager.GetString("MsgInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du deine vorhandenen Daten an den neuen Ort verschieben? (Ja: Umziehen / Nein: Leere Datenbank).
        /// </summary>
        public static string MsgMigrateQuestion {
            get {
                return ResourceManager.GetString("MsgMigrateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speicherort aktualisiert. Die App startet nun neu..
        /// </summary>
        public static string MsgPathUpdatedRestart {
            get {
                return ResourceManager.GetString("MsgPathUpdatedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gespeichert!.
        /// </summary>
        public static string MsgSaved {
            get {
                return ResourceManager.GetString("MsgSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll eine Verknüpfung auf dem Desktop erstellt werden?.
        /// </summary>
        public static string MsgShortcutQuestion {
            get {
                return ResourceManager.GetString("MsgShortcutQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Schreibe hier wichtige Details, Ansprechpartner oder kopiere Infos rein....
        /// </summary>
        public static string PlaceholderNotes {
            get {
                return ResourceManager.GetString("PlaceholderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lehrstellensuchassistenz.
        /// </summary>
        public static string ShortcutDescription {
            get {
                return ResourceManager.GetString("ShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Antwort nach unten.
        /// </summary>
        public static string SortCheckNoResponseBottom {
            get {
                return ResourceManager.GetString("SortCheckNoResponseBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgelehnt nach unten.
        /// </summary>
        public static string SortCheckRejectedBottom {
            get {
                return ResourceManager.GetString("SortCheckRejectedBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbeworben nach oben.
        /// </summary>
        public static string SortCheckUnappliedTop {
            get {
                return ResourceManager.GetString("SortCheckUnappliedTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum: Älteste zuerst.
        /// </summary>
        public static string SortDateAsc {
            get {
                return ResourceManager.GetString("SortDateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum: Neueste zuerst.
        /// </summary>
        public static string SortDateDesc {
            get {
                return ResourceManager.GetString("SortDateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeitet: Alt zuerst.
        /// </summary>
        public static string SortEditAsc {
            get {
                return ResourceManager.GetString("SortEditAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeitet: Neu zuerst.
        /// </summary>
        public static string SortEditDesc {
            get {
                return ResourceManager.GetString("SortEditDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: A → Z.
        /// </summary>
        public static string SortNameAsc {
            get {
                return ResourceManager.GetString("SortNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: Z → A.
        /// </summary>
        public static string SortNameDesc {
            get {
                return ResourceManager.GetString("SortNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgelehnt.
        /// </summary>
        public static string StatusAbgelehnt {
            get {
                return ResourceManager.GetString("StatusAbgelehnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beworben.
        /// </summary>
        public static string StatusBeworben {
            get {
                return ResourceManager.GetString("StatusBeworben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingeladen.
        /// </summary>
        public static string StatusEingeladen {
            get {
                return ResourceManager.GetString("StatusEingeladen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Antwort.
        /// </summary>
        public static string StatusKeineAntwort {
            get {
                return ResourceManager.GetString("StatusKeineAntwort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch nicht beworben.
        /// </summary>
        public static string StatusUnbeworben {
            get {
                return ResourceManager.GetString("StatusUnbeworben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zusage.
        /// </summary>
        public static string StatusZusage {
            get {
                return ResourceManager.GetString("StatusZusage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewerbung.
        /// </summary>
        public static string TextApplication {
            get {
                return ResourceManager.GetString("TextApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Firma hinzufügen.
        /// </summary>
        public static string TitleAddCompany {
            get {
                return ResourceManager.GetString("TitleAddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Details.
        /// </summary>
        public static string TitleCompanyDetails {
            get {
                return ResourceManager.GetString("TitleCompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine Bewerbungen.
        /// </summary>
        public static string TitleCompanyList {
            get {
                return ResourceManager.GetString("TitleCompanyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links verwalten.
        /// </summary>
        public static string TitleManageLinks {
            get {
                return ResourceManager.GetString("TitleManageLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewerbungsvorlagen auswählen.
        /// </summary>
        public static string TitleTemplates {
            get {
                return ResourceManager.GetString("TitleTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen.
        /// </summary>
        public static string TitleWelcome {
            get {
                return ResourceManager.GetString("TitleWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (z.B. Google).
        /// </summary>
        public static string WatermarkLinkName {
            get {
                return ResourceManager.GetString("WatermarkLinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL (https://...).
        /// </summary>
        public static string WatermarkLinkUrl {
            get {
                return ResourceManager.GetString("WatermarkLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen bei der Lehrstellensuchassistenz!
        ///
        ///📌 DEINE DATEIEN &amp; ORDNER:
        ///• Bewerbungsordner: Hier findest du alle deine Dateien (Lebenslauf, Zeugnisse).
        ///• Lebenslauf öffnen: Startet direkt deine hinterlegte PDF-Datei.
        ///
        ///🚀 APP-BEDIENUNG:
        ///• + Firma hinzufügen: Erstellt einen neuen Eintrag.
        ///• Änderungen speichern: Sichert deine Notizen (Hotkey: STRG + S).
        ///• Portale: Schneller Zugriff auf AMS, karriere.at &amp; Co.
        ///
        ///⌨ TASTATUR-TIPPS:
        ///• ENTF: Markierte Firma löschen.
        ///• ESC: Aktuelle Ansicht schließen /  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeInfoContent {
            get {
                return ResourceManager.GetString("WelcomeInfoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erste Schritte &amp; Hilfe.
        /// </summary>
        public static string WelcomeInfoTitle {
            get {
                return ResourceManager.GetString("WelcomeInfoTitle", resourceCulture);
            }
        }
    }
}
