//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lehrstellensuchassistenz.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lehrstellensuchassistenz.Resources.Languages.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzufügen ähnelt.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die + Firma hinzufügen ähnelt.
        /// </summary>
        public static string BtnAddCompany {
            get {
                return ResourceManager.GetString("BtnAddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BEWERBEN! ähnelt.
        /// </summary>
        public static string BtnApplyBig {
            get {
                return ResourceManager.GetString("BtnApplyBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurück ähnelt.
        /// </summary>
        public static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Markierte löschen ähnelt.
        /// </summary>
        public static string BtnBulkDelete {
            get {
                return ResourceManager.GetString("BtnBulkDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner wählen... ähnelt.
        /// </summary>
        public static string BtnChooseFolder {
            get {
                return ResourceManager.GetString("BtnChooseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswahl aufheben ähnelt.
        /// </summary>
        public static string BtnClearSelection {
            get {
                return ResourceManager.GetString("BtnClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fortsetzen ähnelt.
        /// </summary>
        public static string BtnContinue {
            get {
                return ResourceManager.GetString("BtnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Desktop-Verknüpfung erstellen ähnelt.
        /// </summary>
        public static string BtnCreateShortcut {
            get {
                return ResourceManager.GetString("BtnCreateShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einrichtung abschließen ähnelt.
        /// </summary>
        public static string BtnFinishSetup {
            get {
                return ResourceManager.GetString("BtnFinishSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Links verwalten / löschen ähnelt.
        /// </summary>
        public static string BtnManageLinks {
            get {
                return ResourceManager.GetString("BtnManageLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 📂 Bewerbungsordner ähnelt.
        /// </summary>
        public static string BtnOpenAppFolder {
            get {
                return ResourceManager.GetString("BtnOpenAppFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 📄 Lebenslauf öffnen ähnelt.
        /// </summary>
        public static string BtnOpenResume {
            get {
                return ResourceManager.GetString("BtnOpenResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Änderungen speichern ähnelt.
        /// </summary>
        public static string BtnSaveAll {
            get {
                return ResourceManager.GetString("BtnSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leeres Dokument wählen ähnelt.
        /// </summary>
        public static string BtnSelectEmptyTemplate {
            get {
                return ResourceManager.GetString("BtnSelectEmptyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generische Vorlage wählen ähnelt.
        /// </summary>
        public static string BtnSelectGenericTemplate {
            get {
                return ResourceManager.GetString("BtnSelectGenericTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚙ Einstellungen ähnelt.
        /// </summary>
        public static string BtnSettings {
            get {
                return ResourceManager.GetString("BtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cleanup starten ähnelt.
        /// </summary>
        public static string BtnStartCleanup {
            get {
                return ResourceManager.GetString("BtnStartCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 💡 Bewerbungstipps ähnelt.
        /// </summary>
        public static string BtnTippsApplication {
            get {
                return ResourceManager.GetString("BtnTippsApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 📝 Lebenslauftipps ähnelt.
        /// </summary>
        public static string BtnTippsCV {
            get {
                return ResourceManager.GetString("BtnTippsCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verstanden ähnelt.
        /// </summary>
        public static string BtnUnderstood {
            get {
                return ResourceManager.GetString("BtnUnderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigene Vorlage hochladen ähnelt.
        /// </summary>
        public static string BtnUploadCustomTemplate {
            get {
                return ResourceManager.GetString("BtnUploadCustomTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigene Vorlage verwenden ähnelt.
        /// </summary>
        public static string BtnUseCustomTemplate {
            get {
                return ResourceManager.GetString("BtnUseCustomTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App beim Windows-Start automatisch öffnen ähnelt.
        /// </summary>
        public static string CheckAutostart {
            get {
                return ResourceManager.GetString("CheckAutostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Desktop-Verknüpfung erstellen ähnelt.
        /// </summary>
        public static string CheckCreateShortcut {
            get {
                return ResourceManager.GetString("CheckCreateShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Komplette App entfernen (Programmordner löschen) ähnelt.
        /// </summary>
        public static string CheckDeleteAppFolder {
            get {
                return ResourceManager.GetString("CheckDeleteAppFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Benutzerdaten löschen (Firmen, Notizen, Registry) ähnelt.
        /// </summary>
        public static string CheckDeleteUserData {
            get {
                return ResourceManager.GetString("CheckDeleteUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Link konnte nicht geöffnet werden ähnelt.
        /// </summary>
        public static string ErrLinkOpened {
            get {
                return ResourceManager.GetString("ErrLinkOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Erstellen der Verknüpfung: ähnelt.
        /// </summary>
        public static string ErrShortcut {
            get {
                return ResourceManager.GetString("ErrShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bilder (*.png;*.jpg;*.jpeg)|*.png;*.jpg;*.jpeg ähnelt.
        /// </summary>
        public static string FilterImages {
            get {
                return ResourceManager.GetString("FilterImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gefahrenzone ähnelt.
        /// </summary>
        public static string GroupDangerZone {
            get {
                return ResourceManager.GetString("GroupDangerZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daten &amp; Speicher ähnelt.
        /// </summary>
        public static string GroupDataStorage {
            get {
                return ResourceManager.GetString("GroupDataStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemein ähnelt.
        /// </summary>
        public static string GroupGeneral {
            get {
                return ResourceManager.GetString("GroupGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sidebar Quicklinks ähnelt.
        /// </summary>
        public static string GroupQuicklinks {
            get {
                return ResourceManager.GetString("GroupQuicklinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MEINE LINKS ähnelt.
        /// </summary>
        public static string HeaderMyLinks {
            get {
                return ResourceManager.GetString("HeaderMyLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notizen ähnelt.
        /// </summary>
        public static string HeaderNotes {
            get {
                return ResourceManager.GetString("HeaderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PORTALE ähnelt.
        /// </summary>
        public static string HeaderPortals {
            get {
                return ResourceManager.GetString("HeaderPortals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schnell-Einrichtung ähnelt.
        /// </summary>
        public static string HeaderQuickSetup {
            get {
                return ResourceManager.GetString("HeaderQuickSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string HeaderSettings {
            get {
                return ResourceManager.GetString("HeaderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verknüpfung erstellen ähnelt.
        /// </summary>
        public static string HeaderShortcut {
            get {
                return ResourceManager.GetString("HeaderShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠ Hinweis: Nach der Änderung startet die App automatisch neu. ähnelt.
        /// </summary>
        public static string HintRestartNote {
            get {
                return ResourceManager.GetString("HintRestartNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigene Links hinzufügen: ähnelt.
        /// </summary>
        public static string LblAddCustomLinks {
            get {
                return ResourceManager.GetString("LblAddCustomLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erstellt am: ähnelt.
        /// </summary>
        public static string LblCreatedAt {
            get {
                return ResourceManager.GetString("LblCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktueller Speicherort für Benutzerdaten: ähnelt.
        /// </summary>
        public static string LblCurrentStoragePath {
            get {
                return ResourceManager.GetString("LblCurrentStoragePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zuletzt aktualisiert: ähnelt.
        /// </summary>
        public static string LblLastUpdated {
            get {
                return ResourceManager.GetString("LblLastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Link: ähnelt.
        /// </summary>
        public static string LblLink {
            get {
                return ResourceManager.GetString("LblLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string LblName {
            get {
                return ResourceManager.GetString("LblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Firmenbild / Haus ähnelt.
        /// </summary>
        public static string LblPhotoPlaceholderMain {
            get {
                return ResourceManager.GetString("LblPhotoPlaceholderMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Klicken zum Auswählen ähnelt.
        /// </summary>
        public static string LblPhotoPlaceholderSub {
            get {
                return ResourceManager.GetString("LblPhotoPlaceholderSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorschau Eigene Vorlage ähnelt.
        /// </summary>
        public static string LblPreviewCustomTemplate {
            get {
                return ResourceManager.GetString("LblPreviewCustomTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wie heißt die Firma? ähnelt.
        /// </summary>
        public static string LblQuestionCompanyName {
            get {
                return ResourceManager.GetString("LblQuestionCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Links zum Löschen auswählen: ähnelt.
        /// </summary>
        public static string LblSelectLinksToDelete {
            get {
                return ResourceManager.GetString("LblSelectLinksToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: ähnelt.
        /// </summary>
        public static string LblStatus {
            get {
                return ResourceManager.GetString("LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bist du sicher? Die App wird nach dem Cleanup beendet. ähnelt.
        /// </summary>
        public static string MsgCleanupConfirm {
            get {
                return ResourceManager.GetString("MsgCleanupConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du alle markierten Firmen wirklich löschen?
        ///Insgesamt: ähnelt.
        /// </summary>
        public static string MsgConfirmDeleteBulk {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteBulk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Link(s) wirklich entfernen? ähnelt.
        /// </summary>
        public static string MsgConfirmDeleteLinks {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du diese Firma wirklich löschen? ähnelt.
        /// </summary>
        public static string MsgConfirmDeleteSingle {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen bestätigen ähnelt.
        /// </summary>
        public static string MsgConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die ursprüngliche Datei konnte nicht geöffnet werden ähnelt.
        /// </summary>
        public static string MsgErrorOpenOriginal {
            get {
                return ResourceManager.GetString("MsgErrorOpenOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string MsgInfo {
            get {
                return ResourceManager.GetString("MsgInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du deine vorhandenen Daten an den neuen Ort verschieben? (Ja: Umziehen / Nein: Leere Datenbank) ähnelt.
        /// </summary>
        public static string MsgMigrateQuestion {
            get {
                return ResourceManager.GetString("MsgMigrateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speicherort aktualisiert. Die App startet nun neu. ähnelt.
        /// </summary>
        public static string MsgPathUpdatedRestart {
            get {
                return ResourceManager.GetString("MsgPathUpdatedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gespeichert! ähnelt.
        /// </summary>
        public static string MsgSaved {
            get {
                return ResourceManager.GetString("MsgSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll eine Verknüpfung auf dem Desktop erstellt werden? ähnelt.
        /// </summary>
        public static string MsgShortcutQuestion {
            get {
                return ResourceManager.GetString("MsgShortcutQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die   Schreibe hier wichtige Details, Ansprechpartner oder kopiere Infos rein... ähnelt.
        /// </summary>
        public static string PlaceholderNotes {
            get {
                return ResourceManager.GetString("PlaceholderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lehrstellensuchassistenz ähnelt.
        /// </summary>
        public static string ShortcutDescription {
            get {
                return ResourceManager.GetString("ShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Antwort nach unten ähnelt.
        /// </summary>
        public static string SortCheckNoResponseBottom {
            get {
                return ResourceManager.GetString("SortCheckNoResponseBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abgelehnt nach unten ähnelt.
        /// </summary>
        public static string SortCheckRejectedBottom {
            get {
                return ResourceManager.GetString("SortCheckRejectedBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbeworben nach oben ähnelt.
        /// </summary>
        public static string SortCheckUnappliedTop {
            get {
                return ResourceManager.GetString("SortCheckUnappliedTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum: Älteste zuerst ähnelt.
        /// </summary>
        public static string SortDateAsc {
            get {
                return ResourceManager.GetString("SortDateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum: Neueste zuerst ähnelt.
        /// </summary>
        public static string SortDateDesc {
            get {
                return ResourceManager.GetString("SortDateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeitet: Alt zuerst ähnelt.
        /// </summary>
        public static string SortEditAsc {
            get {
                return ResourceManager.GetString("SortEditAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeitet: Neu zuerst ähnelt.
        /// </summary>
        public static string SortEditDesc {
            get {
                return ResourceManager.GetString("SortEditDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: A → Z ähnelt.
        /// </summary>
        public static string SortNameAsc {
            get {
                return ResourceManager.GetString("SortNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: Z → A ähnelt.
        /// </summary>
        public static string SortNameDesc {
            get {
                return ResourceManager.GetString("SortNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abgelehnt ähnelt.
        /// </summary>
        public static string StatusAbgelehnt {
            get {
                return ResourceManager.GetString("StatusAbgelehnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beworben ähnelt.
        /// </summary>
        public static string StatusBeworben {
            get {
                return ResourceManager.GetString("StatusBeworben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eingeladen ähnelt.
        /// </summary>
        public static string StatusEingeladen {
            get {
                return ResourceManager.GetString("StatusEingeladen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Antwort ähnelt.
        /// </summary>
        public static string StatusKeineAntwort {
            get {
                return ResourceManager.GetString("StatusKeineAntwort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Noch nicht beworben ähnelt.
        /// </summary>
        public static string StatusUnbeworben {
            get {
                return ResourceManager.GetString("StatusUnbeworben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zusage ähnelt.
        /// </summary>
        public static string StatusZusage {
            get {
                return ResourceManager.GetString("StatusZusage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bewerbung ähnelt.
        /// </summary>
        public static string TextApplication {
            get {
                return ResourceManager.GetString("TextApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Firma hinzufügen ähnelt.
        /// </summary>
        public static string TitleAddCompany {
            get {
                return ResourceManager.GetString("TitleAddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Firma Details ähnelt.
        /// </summary>
        public static string TitleCompanyDetails {
            get {
                return ResourceManager.GetString("TitleCompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Bewerbungen ähnelt.
        /// </summary>
        public static string TitleCompanyList {
            get {
                return ResourceManager.GetString("TitleCompanyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Links verwalten ähnelt.
        /// </summary>
        public static string TitleManageLinks {
            get {
                return ResourceManager.GetString("TitleManageLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bewerbungsvorlagen auswählen ähnelt.
        /// </summary>
        public static string TitleTemplates {
            get {
                return ResourceManager.GetString("TitleTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen ähnelt.
        /// </summary>
        public static string TitleWelcome {
            get {
                return ResourceManager.GetString("TitleWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name (z.B. Google) ähnelt.
        /// </summary>
        public static string WatermarkLinkName {
            get {
                return ResourceManager.GetString("WatermarkLinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die URL (https://...) ähnelt.
        /// </summary>
        public static string WatermarkLinkUrl {
            get {
                return ResourceManager.GetString("WatermarkLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen bei der Lehrstellensuchassistenz!
        ///
        ///📌 DEINE DATEIEN &amp; ORDNER:
        ///• Bewerbungsordner: Hier findest du alle deine Dateien (Lebenslauf, Zeugnisse).
        ///• Lebenslauf öffnen: Startet direkt deine hinterlegte PDF-Datei.
        ///
        ///🚀 APP-BEDIENUNG:
        ///• + Firma hinzufügen: Erstellt einen neuen Eintrag.
        ///• Änderungen speichern: Sichert deine Notizen (Hotkey: STRG + S).
        ///• Portale: Schneller Zugriff auf AMS, karriere.at &amp; Co.
        ///
        ///⌨ TASTATUR-TIPPS:
        ///• ENTF: Markierte Firma löschen.
        ///• ESC: Aktuelle Ansicht schließen / Zurück.
        ///• STR [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string WelcomeInfoContent {
            get {
                return ResourceManager.GetString("WelcomeInfoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erste Schritte &amp; Hilfe ähnelt.
        /// </summary>
        public static string WelcomeInfoTitle {
            get {
                return ResourceManager.GetString("WelcomeInfoTitle", resourceCulture);
            }
        }
    }
}
